name: faf5-supply-chain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.1.0
  - scipy>=1.9.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  - plotly>=5.0.0
  - bokeh>=2.4.0
  - xgboost>=1.6.0
  - pip
  - pip:
    - ipykernel 